/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.microkernel.presentation;

import co.unicauca.microkernel.infra.Publisher;
import co.unicauca.microkernel.business.ServicioMedicion;
import co.unicauca.microkernel.business.ProductService;
import co.unicauca.microkernel.common.entities.Medicion;
import co.unicauca.microkernel.common.entities.Product;
import com.google.gson.Gson;
import java.util.List;
import javax.swing.JPanel;

public class GUISendProduct extends javax.swing.JFrame{
    
    
    //private ProductService productService;
    private ServicioMedicion servicioMedicion;
    Product selectedProduct = Product.getEjemplar();
    List<Product> products;
    Publisher publisher;

    /**
     * Creates new form GUISendProduct
     */
    public GUISendProduct() {
        initComponents();
        ProductService productService = new ProductService();
        publisher = new Publisher();
        products = productService.getAll();
        for (int index = 0; index < products.size(); index++) {
        jComboBox1.addItem(products.get(index).getName());
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtLargo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDiametro = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Medicion calidad producto");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Seleccione el producto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 133, 63));

        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 133, 63));

        jLabel3.setText("Indique el largo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 63));
        jPanel1.add(txtLargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 130, 60));

        jLabel4.setText("Indique Referencia");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 63));
        jPanel1.add(txtReferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 133, 63));

        jLabel5.setText("Indique Diametro");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 133, 63));
        jPanel1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 160, 50));

        jLabel7.setText("Estado producto");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));
        jPanel1.add(txtDiametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 130, 60));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Calcular Calidad");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Product selectedProduct = products.get(this.jComboBox1.getSelectedIndex());
        selectedProduct = products.get(this.jComboBox1.getSelectedIndex());
        int s = jComboBox1.getSelectedIndex();
        s=s+1;
        String code="";
        if(s == 1){
            code = "cz";
        }else{
            code = "gs";
        }
        selectedProduct.setLargo(Double.parseDouble(txtLargo.getText()));
        selectedProduct.setDiametro(Double.parseDouble(txtDiametro.getText()));
        selectedProduct.setReferencia(txtReferencia.getText());
        Medicion entidadMedicion = new Medicion(selectedProduct,code);
        try {
            servicioMedicion = new ServicioMedicion();
            String estado = servicioMedicion.calcularMedicionEstandar(entidadMedicion);
           
            selectedProduct.setEstado(estado);
            selectedProduct = products.get(this.jComboBox1.getSelectedIndex());
            Gson gson = new Gson();
            String msgJson = gson.toJson(selectedProduct);
            publisher.publish(msgJson);
            txtLargo.setText("");
            txtDiametro.setText("");
            txtReferencia.setText("");
            txtEstado.setText(" Registrado ");
            
            
            
        } catch (Exception exception) {
            System.out.println("No fue posible verificar el estado del producto. " + exception.getMessage());
        }

        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDiametro;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtLargo;
    private javax.swing.JTextField txtReferencia;
    // End of variables declaration//GEN-END:variables

}
